---
abstract: 'Plugin system based on roles'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::Class: 0
  Test::Class::Load: 0
  Test::More: 0.94
  Test::Most: 0
  parent: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Brickyard
provides:
  Brickyard:
    file: lib/Brickyard.pm
    version: 1.103640
  Brickyard::PluginContainer:
    file: lib/Brickyard/PluginContainer.pm
    version: 1.103640
  Brickyard::Role::Plugin:
    file: lib/Brickyard/Role/Plugin.pm
    version: 1.103640
  Brickyard::Role::PluginBundle:
    file: lib/Brickyard/Role/PluginBundle.pm
    version: 1.103640
requires:
  File::Slurp: 0
  Module::Load: 0
  Role::Basic: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Brickyard
  homepage: http://search.cpan.org/dist/Brickyard/
  repository: git://github.com/hanekomu/Brickyard.git
version: 1.103640
